### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by walkie15** [365CSI/iCSR#10]
Hello,

I am trying to implement your ICSR solution but I have some troubles :
I have added in style library the iCSR.js file and another file for templates and to call "iCSR.Me ..." but it seems not working because nothing is happens.

Do you have any idea ?
Thanks.

**Comment by Danny-Engelman** [comment]
Can you post your full code.

To check if iCSR is loaded, browse to the View, open F12 developer tools and type 'icsr' in the console. If it says undefined you need to load the icsr.js library

**Comment by Danny-Engelman** [comment]
Can you try the http://ViewMaster365.com installer, it installs iCSR and templates and CSR code in just a couple of clicks

**Comment by walkie15** [comment]
Thank you for your reply.
I have tried to use the ViewMaster365 but I have an error message when I activate the Bookmarklet :
![error](https://cloud.githubusercontent.com/assets/20657526/17136032/46a04538-5333-11e6-987b-17d1f98652e5.png)

**Comment by walkie15** [comment]
I am site collection administrator on this site

**Comment by 365CSI** [comment]
Which browser are you using?

Can we do a Skype session? You can contact me at: danny@365csi.nl 
I have to see the F12 console to see why what is going on.

**Comment by walkie15** [comment]
Thank for your help.
I am working on it in a company and the proxy is blocking Skype session unfortunately...
I am using Internet Explorer 11.
I can try the F12 console and send you a screen shot.

**Comment by walkie15** [comment]
![icsr2](https://cloud.githubusercontent.com/assets/20657526/17136371/27a00298-5335-11e6-8446-7e268e6d15b5.png)

**Comment by Danny-Engelman** [comment]
The file: property should reference its own js file (the icsr_demo.js file) , this is a SharePoint requirement when MDS is enabled, so SharePoint knows which files to execute on MDS navigation.

the svgcircle is not available in the open source version, my mistake with the documentation

View: iCSR.Priority

is all you need

Did you load the icsr.js library itself? Just like with jquery you have to add the library to your environment.

If the ViewMaster Bookmarklet (install iCSR in 10 seconds) did not work because of insufficient rights then the LinkManager won't work either (its the same code just different UI)
I would have to see the trace from the F12 console to see why it does not work for you

**Comment by walkie15** [comment]
![iscr](https://cloud.githubusercontent.com/assets/20657526/17136675/06990e6c-5337-11e6-8a97-ad9ed22d61b2.png)

**Comment by Danny-Engelman** [comment]
You are making typos in filenames, which should be no problem, just make sure you use **iCSR** in code.

## Step #1 - check if icsr.js (ISCR.js for you) is loaded:
1. Open the F12 console in this view
2. type 'icsr' and enter
3. If the response is something about undefined then load icsr just like you load jQuery into your SiteCollection

Is icsr loaded??

**Comment by walkie15** [comment]
I just send you a WebEx invitation to your mail.

I have checked if ISCR.js (for me) is loaded and I have send you a screen shot 19 minutes ago. I think it is loaded : 
![icsr2](https://cloud.githubusercontent.com/assets/20657526/17136880/1f14e3d4-5338-11e6-904c-69db44229862.png)

**Comment by walkie15** [comment]
![icsr3](https://cloud.githubusercontent.com/assets/20657526/17136958/90d27c2a-5338-11e6-962b-fa6d6b9e5fd6.png)

**Comment by Danny-Engelman** [comment]
I can only do Skype (and normally only for customers)

icsr.js needs to be loaded **before** you can use it in icsr_demo.js

Its just like jQuery.. you need to load jQuery before you can use its code.

You can manually set the JSLink on the ListView webpart to load 2 files... icsr.js first, then icsr_demo.js, you can use the ~sitecollection reference (see Microsofts documentation) and must seperate filereferences with the | (pipe) symbol

**Comment by walkie15** [comment]
![iscr4](https://cloud.githubusercontent.com/assets/20657526/17137095/939683f6-5339-11e6-82c0-b762715d9a24.png)

**Comment by walkie15** [comment]
![iscr5](https://cloud.githubusercontent.com/assets/20657526/17137105/a297ed9a-5339-11e6-8614-7b8a9a32c3da.png)

**Comment by walkie15** [comment]
Is it better ? Unfortunately it seems not working as well

**Comment by Danny-Engelman** [comment]
Your screenshots are still on the Debugger Tab and not the F12 Console Tab (one to the left)

Type: iCSR
in the console, hit enter

If it says "undefined" then you have not loaded icsr.js **before** icsr_demo.js (and thats why the Debugger pops open... becuase iCSR is undefined)

**Comment by walkie15** [comment]
![iscr6](https://cloud.githubusercontent.com/assets/20657526/17137767/396affde-533d-11e6-9238-c564c987a1f3.png)

yes I have nothing in the console, I will try to correct the typo of filename and see if it's better.

**Comment by walkie15** [comment]
I am little desperate, this is the situation now : 
![iscr7](https://cloud.githubusercontent.com/assets/20657526/17138135/22b79f3e-533f-11e6-97ee-31f4efe739e0.png)

![iscr8](https://cloud.githubusercontent.com/assets/20657526/17138148/2ceb7caa-533f-11e6-8dde-c9fbe81d1c47.png)

And the JS Link of the webpart is : 
~sitecollection/Style Library/ICSR/icsrjs|~sitecollection/Style Library/ICSR/icsr_demo.js

**Comment by walkie15** [comment]
~sitecollection/Style Library/ICSR/icsr.js|~sitecollection/Style Library/ICSR/icsr_demo.js

**Comment by walkie15** [comment]
Ok I understand, it's not working in Internet Explorer 11 ! 
![ie](https://cloud.githubusercontent.com/assets/20657526/17138374/455f8e9c-5340-11e6-897a-b7a6b04df214.png)

It's working in Firefox...
![firefox](https://cloud.githubusercontent.com/assets/20657526/17138378/48937d62-5340-11e6-8944-5695f380e18c.png)

Is it compatible with IE 11?

**Comment by Danny-Engelman** [comment]
version 3 works on IE11, that new version was scheduled for June, but Microsoft has disabled UserCustomActions of Office365... So it has to wait for the New SharePoint Framework to become public.

I am now (re)testing version 2.1 (public on github) on IE11..

**Comment by Danny-Engelman** [comment]
See https://github.com/365CSI/iCSR/issues/11
it is tested and works in Edge/IE11

Please check your F12 Dev **Console** and paste any findings in the specific IE11 issue: https://github.com/365CSI/iCSR/issues/11

**Comment by 365CSI** [comment]
Closed.

Also see: Issue #11  - https://github.com/365CSI/iCSR/issues/11
