### ISSUE TITLE
iCSR js is not working on IE 10 and 11

### ISSUE THREAD

**Issue by Danny-Engelman** [365CSI/iCSR#11]
**Solution:** 

**icsr.js** does extensive logging to the F12 Console, only the Chrome browser can do colored output to the console

Use **icsr.min.js** (no console code at all) for Production and developing on IE

<hr>

iCSR 2.1 was tested in Edge/IE11

Check your F12 Console Tab for errors with icsr.js loaded (the minified version does not trace to the console)

![](http://i.imgur.com/sEh33vr.jpg)

**Comment by walkie15** [comment]
I don't have any information in my console both IE or FireFox : 
![iscr9](https://cloud.githubusercontent.com/assets/20657526/17142865/ea1eae5c-5351-11e6-95ec-d3752f22e10a.png)

**Comment by Danny-Engelman** [comment]
Unless you used icsr.min.js which does not log to the console;
if there is nothing about icsr in the console on pageload, it was not loaded.

Add icsr.js as JSLink or load it with a UserCustomAction
See the section "Support Tools" at the bottom of the page at: https://github.com/365CSI/iCSR

**Comment by walkie15** [comment]
Hello ! I have succeeded to see info in the console and indeed in IE 11 I have one issue : 
![iscr10](https://cloud.githubusercontent.com/assets/20657526/17171966/39f8e2a2-53f3-11e6-80f4-ab0d943fa2eb.png)

**Comment by Danny-Engelman** [comment]
No, see top right of your screenshot.. 
You are NOT running IE11 but IE10 (or a higher version in IE10 mode)
Which indeed, does not have console.group support... 

Most likely this is cause because you run the website in Compatiblity View:
https://support.microsoft.com/en-us/help/17472/windows-internet-explorer-11-fix-site-display-problems-compatibility-view

**Fix:**
Instead of using **icsr.js** you should use **icsr.min.js** which does not log anything to the console.

I have fixed it for a future icsr version (but am waiting till Microsoft releases the SharePoint Framework)

**Comment by Danny-Engelman** [comment]
No, I am not going to patch anything.

Instead of using **icsr.js** you should use **icsr.min.js** which does not log anything to the console.

**Comment by walkie15** [comment]
Thank you very much, using icsr-min.js has fixed the problem.
All is working using FireFox or IE 11.
:+1:

**Comment by 365CSI** [comment]
Closed Issue
Issue was due to IE10 not supporting `console.group` statement
