### ISSUE TITLE
The git  (icsr.js) is totally different form the installed icsr.js we blocked the script!!

### ISSUE THREAD

**Issue by twerfally** [365CSI/iCSR#12]
[U

[Uploading icsr.js.pdf…]()

ploading icsr.js.pdf…]()

Please check out the file and kindly just tell me why its not identical with the published code on your github.
 Thanks

**Comment by Danny-Engelman** [comment]
You posted a link with a minimal or unclear description.
Can you please verify you are not a spam-bot.
What is the result of 1+2?

**Comment by twerfally** [comment]
The result is SQRT(3 \* 3 / 3 \* 3), so in the last post i did try to upload the icsr.js as pdf file! but this unclear post come from GitHub it self you can consider it not my post description.
The story here is: that after installing your iCSR to my test sharepoint server i did compare the uploaded icsr.js on Style Library with the published iscr.js in your page i found it completely different, what i expected that a CSR script to change the layout of tasks web part, but i couldn't understand the script purpose!
First i just want to know the difference between the two mentioned scripts.
Thanks and sorry for confusion.

**Comment by twerfally** [comment]
This below code got from icsr.js installed version, would you explain the purpose please:

iCSR.ensureDigest = function () {
    /\* never let digest expire, get a new one every 20 minutes */
    iCSR.$Xdigest || window.setInterval(function () {
        iCSR.ensureDigest();
    }, 12e5); // jshint ignore:line
    //document.getElementById('__REQUESTDIGEST').value
    //RequestDigest dynamically http://www.wictorwilen.se/sharepoint-2013-how-to-refresh-the-request-digest-value-in-javascript

```
if (typeof _spPageContextInfo === 'object') {
    iCSR.$xhr(_spPageContextInfo.webAbsoluteUrl + '/_api/contextinfo', 'POST').then(function (data) {
        iCSR.$Xdigest = data.GetContextWebInformation.FormDigestValue;
        console.warn('Rerieved new FormDigest value', iCSR.$Xdigest.split(',')[1], data);
    });
}
```

};

iCSR.userProperties = function () {
    return iCSR.$ajax(_spPageContextInfo.siteAbsoluteUrl + "/_api/SP.UserProfiles.PeopleManager/GetMyProperties").then(function (results) {
        var upProps = results.UserProfileProperties;
        upProps.results.forEach(function (prop) {
            iCSR.userProperties[prop.Key] = prop.Value;
        });
    });
};

console.warn((function () {        // EXCLUDE code from minified version
    window.testAPI = function (uri, doFunc) {
        doFunc = doFunc || function (data) {
                console.info('testAPI', uri);
                var dataType = typeof data;
                var isArray = Array.isArray(data);
                console.info(dataType, isArray ? 'isArray:' + data.length + ' items' : Object.keys(data).length + ' keys', data);
            };
        if (uri.indexOf('http') < 0) {
            uri = String.format("{0}/_api/web/{1}", _spPageContextInfo.webAbsoluteUrl, uri || '');
        }

```
    iCSR.$xhr(uri).then(doFunc).catch(function (e) {
        try {
            console.error(e.message.value);
        } catch (e) { // jshint ignore:line
        }
        console.error(e);
    });
};
window.testSearch = function (uri, doFunc) {
    doFunc = doFunc || function (data) {
            console.info('testSearch', uri);
            console.info(data.results.length, ' results (first 10 shown)');
            data.results.forEach(function (resultRow, index) {
                if (index < 10) {
                    console.log(index, resultRow);
                }
            });
        };
    iCSR.search(uri).then(doFunc).catch(function (e) {
        try {
            console.error(e.message.value);
        } catch (e) { // jshint ignore:line
        }
        console.error(e);
    });

};
return "testAPI( ) available";
```

})());

**Comment by Danny-Engelman** [comment]
Hmm.. looks like you are using an icsr.js version newer than the 2.1 published here on Github.

The code is for handling REST calls, is under development and MIGHT be part of a future OpenSource version.

How did you install this code? With the LinkManager? It looks like that deploys my dev code from my own server.. my mistake

Delete the version from the Style Library and manually add version 2.1 from Github

**Comment by twerfally** [comment]
i did delete of course this version and blocked the script, but still i have javascript reference i want to remove it, its in every page when you view the inspected elements via F12, where this reference is registered? i need to remove it, so please save my time to do so:

`<script type="text/javascript" src="https://365csi.nl/icsr/examples/icsr_demo.js"></script>`

its referencing a script located at your site, which is "unacceptable" in our policy.

i found this link `http://sharepoint.stackexchange.com/questions/171571/is-sod-async-so-the-dom-is-sometimes-already-created-before-csr-runs` explaining my request, so i need the de-register code from your side and any clean up procedures.

**Comment by twerfally** [comment]
<script type="text/javascript" src="https://365csi.nl/icsr/examples/icsr_demo.js"></script>

**Comment by twerfally** [comment]
> <script type="text/javascript" src="https://365csi.nl/icsr/examples/icsr_demo.js"></script>>

**Comment by twerfally** [comment]
`<script type="text/javascript" src="https://365csi.nl/icsr/examples/icsr_demo.js"></script>`

**Comment by Danny-Engelman** [comment]
It is a UserCustomAction ScriptLink (SharePoint technology since version 2010)

You used the LinkManager to install iCSR http://365csi.nl/icsr/linkmanager/

You can also use the LinkManager to delete UserCustomActions
 If you do no want to use the LinkManager see the references to other tooling at the bottom of http://icsr.github.io

**Comment by 365CSI** [comment]
Closing this issue.

Warning to others: Be sure you understand the implications of installing Open Source software.
