### ISSUE TITLE
Not working with French date

### ISSUE THREAD

**Issue by walkie15** [365CSI/iCSR#13]
Hello,
Do you have a version working with both SharePoint English and French site ?
Indeed when the end date of tasks is in French format,  the days past/left is incorrect.
Thanks.

**Comment by 365CSI** [comment]
No, it's open source so you can add it yourself.. better yet, convert the date before you feed it to icsr from your own csr code

On Sep 26, 2016 11:17 AM, walkie15 notifications@github.com wrote:

Hello,
Do you have a version working with both SharePoint English and French site ?
Indeed when the end date of tasks is in French format, the days past/left is incorrect.
Thanks.

##
