### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by Gennady-G** [365CSI/iCSR#14]
Greetings Danny!

Trying to install Your iCSR lib from bookmarklet, on subsite. It hangs:

![2017-11-03_142434](https://user-images.githubusercontent.com/5569346/32373585-9790248a-c0a2-11e7-8b03-dbd04b3b92f1.png)

![2017-11-03_142737](https://user-images.githubusercontent.com/5569346/32373665-0826fe30-c0a3-11e7-9f60-83660139b6d6.png)

Can provide more info, if You tell me what You need

**upd**.: Library was restored from template (from list on same web)

Best regards,     
Gennady

**Comment by Danny-Engelman** [comment]
I have left the Microsoft world,
one of the reason being Microsoft does not support (their own) CSR technology any longer in recent "Modern Experience" SharePoint versions.

Looks like the one-button Bookmarklet install for ViewMaster365.com is broken (I should take down that site).
You can add icsr.js from Github by hand just like you did the AmbellSolutions CSR links in your env.

Also checkout the Chrome Extension SPEditor and Cisar (not by me)

SPEditor allows editting of CSR links (Site and Web Custom Actions)
Cisar is for editting CSR files

**Comment by Gennady-G** [comment]
>I have left the Microsoft world

:(

> Microsoft does not support (their own) CSR technology

There is cool old post about it :)
https://www.joelonsoftware.com/2002/01/06/fire-and-motion/

> You can add icsr.js from Github by hand just like you did the AmbellSolutions CSR links in your env.
> Also checkout the Chrome Extension SPEditor and Cisar (not by me)

Yes, these are Scriptlinks deployed with SP Chrome editor) 

> Looks like the one-button Bookmarklet install for ViewMaster365.com is broken

Ok. I'll try to install manually

Thank You Danny!

**Comment by Gennady-G** [comment]
Hi Danny!

What is the order of these libs? I get "Type is not defined" (Publishing is not activated, MDS deactivated)

![2017-11-05_202419](https://user-images.githubusercontent.com/5569346/32417827-d59e3548-c267-11e7-8b89-eefd3813cbeb.png)

![2017-11-05_202427](https://user-images.githubusercontent.com/5569346/32417831-d9f21f10-c267-11e7-9721-407989b7d3a3.png)

**Comment by Gennady-G** [comment]
Hmm, think I resolved. Included 

> https://ajax.aspnetcdn.com/ajax/4.0/1/MicrosoftAjax.js

before iCSR
